server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_URL:localhost}:3307/booking_db
    username: ${SPRING_DATASOURCE_USERNAME:${MYSQL_USER}}
    password: ${SPRING_DATASOURCE_PASSWORD:${MYSQL_PASSWORD}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


ru:
  ikbo2019:
    bookinghotel:
      jwtExpiration: 3600

